import { RegisteredComponentPlaceholder } from "./componentHost";
import type { EditorComponentDefinition } from "./componentTypes";

export const builtinEditorComponents: EditorComponentDefinition[] = [
  {
    id: "project.explorer",
    title: "Project Explorer",
    category: "explorer",
    domain: "project",
    icon: "folder",
    description: "Project file tree and mod structure.",
    placement: { kind: "leftDock" },
    defaultPlacement: { kind: "leftDock" },
    allowedPlacements: ["leftDock", "rightDock", "floatingPanel"],
    requiredContext: ["editorSession"],
    canDock: true,
    canFloat: true,
    canOpenInWindow: false,
    canOpenInCenterTabs: false,
    singleton: true,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "assets.browser",
    title: "Assets",
    category: "explorer",
    domain: "assets",
    icon: "package",
    description: "Asset type browser and future thumbnail index.",
    placement: { kind: "leftDock" },
    defaultPlacement: { kind: "leftDock" },
    allowedPlacements: ["leftDock", "rightDock", "floatingPanel"],
    requiredContext: ["editorSession"],
    canDock: true,
    canFloat: true,
    canOpenInWindow: false,
    canOpenInCenterTabs: false,
    singleton: true,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "scenes.browser",
    title: "Scenes",
    category: "explorer",
    domain: "scene",
    icon: "play",
    description: "Scene navigation list.",
    placement: { kind: "leftDock" },
    defaultPlacement: { kind: "leftDock" },
    allowedPlacements: ["leftDock", "rightDock", "floatingPanel"],
    requiredContext: ["editorSession"],
    canDock: true,
    canFloat: true,
    canOpenInWindow: false,
    canOpenInCenterTabs: false,
    singleton: true,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "scripts.browser",
    title: "Scripts",
    category: "explorer",
    domain: "scripting",
    icon: "terminal",
    description: "Scripts and packages navigation.",
    placement: { kind: "leftDock" },
    defaultPlacement: { kind: "leftDock" },
    allowedPlacements: ["leftDock", "rightDock", "floatingPanel"],
    requiredContext: ["editorSession"],
    canDock: true,
    canFloat: true,
    canOpenInWindow: false,
    canOpenInCenterTabs: false,
    singleton: true,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "scene.hierarchy",
    title: "Scene Hierarchy",
    category: "explorer",
    domain: "scene",
    icon: "list-tree",
    placement: { kind: "leftDock" },
    defaultPlacement: { kind: "leftDock" },
    allowedPlacements: ["leftDock", "rightDock", "floatingPanel"],
    requiredContext: ["selectedScene"],
    canDock: true,
    canFloat: true,
    canOpenInWindow: false,
    canOpenInCenterTabs: false,
    singleton: true,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "project.overview",
    title: "Mod Overview",
    category: "workspace",
    domain: "project",
    icon: "box",
    description: "Summary of the active mod.",
    placement: { kind: "centerTab" },
    defaultPlacement: { kind: "centerTab" },
    allowedPlacements: ["centerTab", "floatingPanel", "window"],
    requiredContext: ["editorSession"],
    canDock: false,
    canFloat: true,
    canOpenInWindow: true,
    canOpenInCenterTabs: true,
    singleton: true,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "project.capabilities",
    title: "Capabilities",
    category: "workspace",
    domain: "project",
    icon: "box",
    description: "Capabilities declared by the active mod.",
    placement: { kind: "centerTab" },
    defaultPlacement: { kind: "centerTab" },
    allowedPlacements: ["centerTab", "floatingPanel", "window"],
    requiredContext: ["editorSession"],
    canDock: false,
    canFloat: true,
    canOpenInWindow: true,
    canOpenInCenterTabs: true,
    singleton: true,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "project.dependencies",
    title: "Dependencies",
    category: "workspace",
    domain: "project",
    icon: "package",
    description: "Dependency state for the active mod.",
    placement: { kind: "centerTab" },
    defaultPlacement: { kind: "centerTab" },
    allowedPlacements: ["centerTab", "floatingPanel", "window"],
    requiredContext: ["editorSession"],
    canDock: false,
    canFloat: true,
    canOpenInWindow: true,
    canOpenInCenterTabs: true,
    singleton: true,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "scene.preview",
    title: "Scene Preview",
    category: "preview",
    domain: "preview",
    subdomain: "scene",
    icon: "play",
    placement: { kind: "centerTab" },
    defaultPlacement: { kind: "centerTab" },
    allowedPlacements: ["centerTab", "floatingPanel", "window"],
    requiredContext: ["selectedScene"],
    canDock: false,
    canFloat: true,
    canOpenInWindow: true,
    canOpenInCenterTabs: true,
    singleton: false,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "file.manifest",
    title: "Manifest",
    category: "editor",
    domain: "modding",
    icon: "box",
    placement: { kind: "centerTab" },
    defaultPlacement: { kind: "centerTab" },
    allowedPlacements: ["centerTab", "floatingPanel", "window"],
    requiredContext: ["editorSession"],
    canDock: false,
    canFloat: true,
    canOpenInWindow: true,
    canOpenInCenterTabs: true,
    singleton: false,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "file.scene",
    title: "Scene",
    category: "editor",
    domain: "scene",
    icon: "play",
    placement: { kind: "centerTab" },
    defaultPlacement: { kind: "centerTab" },
    allowedPlacements: ["centerTab", "floatingPanel", "window"],
    requiredContext: ["editorSession"],
    canDock: false,
    canFloat: true,
    canOpenInWindow: true,
    canOpenInCenterTabs: true,
    singleton: false,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "file.scene-script",
    title: "Scene Script",
    category: "editor",
    domain: "scripting",
    icon: "terminal",
    placement: { kind: "centerTab" },
    defaultPlacement: { kind: "centerTab" },
    allowedPlacements: ["centerTab", "floatingPanel", "window"],
    requiredContext: ["editorSession"],
    canDock: false,
    canFloat: true,
    canOpenInWindow: true,
    canOpenInCenterTabs: true,
    singleton: false,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "file.package",
    title: "Package",
    category: "editor",
    domain: "scripting",
    icon: "package",
    placement: { kind: "centerTab" },
    defaultPlacement: { kind: "centerTab" },
    allowedPlacements: ["centerTab", "floatingPanel", "window"],
    requiredContext: ["editorSession"],
    canDock: false,
    canFloat: true,
    canOpenInWindow: true,
    canOpenInCenterTabs: true,
    singleton: false,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "file.script",
    title: "Script",
    category: "editor",
    domain: "scripting",
    icon: "terminal",
    placement: { kind: "centerTab" },
    defaultPlacement: { kind: "centerTab" },
    allowedPlacements: ["centerTab", "floatingPanel", "window"],
    requiredContext: ["editorSession"],
    canDock: false,
    canFloat: true,
    canOpenInWindow: true,
    canOpenInCenterTabs: true,
    singleton: false,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "file.texture",
    title: "Texture",
    category: "preview",
    domain: "assets",
    icon: "image",
    placement: { kind: "centerTab" },
    defaultPlacement: { kind: "centerTab" },
    allowedPlacements: ["centerTab", "floatingPanel", "window"],
    requiredContext: ["editorSession"],
    canDock: false,
    canFloat: true,
    canOpenInWindow: true,
    canOpenInCenterTabs: true,
    singleton: false,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "file.sprite",
    title: "Sprite",
    category: "editor",
    domain: "rendering_2d",
    icon: "image",
    placement: { kind: "centerTab" },
    defaultPlacement: { kind: "centerTab" },
    allowedPlacements: ["centerTab", "floatingPanel", "window"],
    requiredContext: ["editorSession"],
    canDock: false,
    canFloat: true,
    canOpenInWindow: true,
    canOpenInCenterTabs: true,
    singleton: false,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "file.atlas",
    title: "Atlas",
    category: "editor",
    domain: "rendering_2d",
    icon: "image",
    placement: { kind: "centerTab" },
    defaultPlacement: { kind: "centerTab" },
    allowedPlacements: ["centerTab", "floatingPanel", "window"],
    requiredContext: ["editorSession"],
    canDock: false,
    canFloat: true,
    canOpenInWindow: true,
    canOpenInCenterTabs: true,
    singleton: false,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "file.tileset",
    title: "Tileset",
    category: "editor",
    domain: "tileset",
    icon: "layers",
    placement: { kind: "centerTab" },
    defaultPlacement: { kind: "centerTab" },
    allowedPlacements: ["centerTab", "floatingPanel", "window"],
    requiredContext: ["editorSession"],
    canDock: false,
    canFloat: true,
    canOpenInWindow: true,
    canOpenInCenterTabs: true,
    singleton: false,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "file.tilemap",
    title: "Tilemap",
    category: "editor",
    domain: "tilemap",
    icon: "layers",
    placement: { kind: "centerTab" },
    defaultPlacement: { kind: "centerTab" },
    allowedPlacements: ["centerTab", "floatingPanel", "window"],
    requiredContext: ["editorSession"],
    canDock: false,
    canFloat: true,
    canOpenInWindow: true,
    canOpenInCenterTabs: true,
    singleton: false,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "file.audio",
    title: "Audio",
    category: "preview",
    domain: "audio",
    icon: "play",
    placement: { kind: "centerTab" },
    defaultPlacement: { kind: "centerTab" },
    allowedPlacements: ["centerTab", "floatingPanel", "window"],
    requiredContext: ["editorSession"],
    canDock: false,
    canFloat: true,
    canOpenInWindow: true,
    canOpenInCenterTabs: true,
    singleton: false,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "file.font",
    title: "Font",
    category: "preview",
    domain: "assets",
    icon: "type",
    placement: { kind: "centerTab" },
    defaultPlacement: { kind: "centerTab" },
    allowedPlacements: ["centerTab", "floatingPanel", "window"],
    requiredContext: ["editorSession"],
    canDock: false,
    canFloat: true,
    canOpenInWindow: true,
    canOpenInCenterTabs: true,
    singleton: false,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "file.particle",
    title: "Particles",
    category: "editor",
    domain: "particles_2d",
    icon: "gauge",
    placement: { kind: "centerTab" },
    defaultPlacement: { kind: "centerTab" },
    allowedPlacements: ["centerTab", "floatingPanel", "window"],
    requiredContext: ["editorSession"],
    canDock: false,
    canFloat: true,
    canOpenInWindow: true,
    canOpenInCenterTabs: true,
    singleton: false,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "file.ui",
    title: "UI Layout",
    category: "editor",
    domain: "editor",
    icon: "box",
    placement: { kind: "centerTab" },
    defaultPlacement: { kind: "centerTab" },
    allowedPlacements: ["centerTab", "floatingPanel", "window"],
    requiredContext: ["editorSession"],
    canDock: false,
    canFloat: true,
    canOpenInWindow: true,
    canOpenInCenterTabs: true,
    singleton: false,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "file.input",
    title: "Input Map",
    category: "editor",
    domain: "editor",
    icon: "settings",
    placement: { kind: "centerTab" },
    defaultPlacement: { kind: "centerTab" },
    allowedPlacements: ["centerTab", "floatingPanel", "window"],
    requiredContext: ["editorSession"],
    canDock: false,
    canFloat: true,
    canOpenInWindow: true,
    canOpenInCenterTabs: true,
    singleton: false,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "file.config",
    title: "Config",
    category: "editor",
    domain: "editor",
    icon: "box",
    placement: { kind: "centerTab" },
    defaultPlacement: { kind: "centerTab" },
    allowedPlacements: ["centerTab", "floatingPanel", "window"],
    requiredContext: ["editorSession"],
    canDock: false,
    canFloat: true,
    canOpenInWindow: true,
    canOpenInCenterTabs: true,
    singleton: false,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "file.text",
    title: "Text",
    category: "editor",
    domain: "editor",
    icon: "terminal",
    placement: { kind: "centerTab" },
    defaultPlacement: { kind: "centerTab" },
    allowedPlacements: ["centerTab", "floatingPanel", "window"],
    requiredContext: ["editorSession"],
    canDock: false,
    canFloat: true,
    canOpenInWindow: true,
    canOpenInCenterTabs: true,
    singleton: false,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "file.binary",
    title: "Unsupported File",
    category: "workspace",
    domain: "assets",
    icon: "alert-triangle",
    placement: { kind: "centerTab" },
    defaultPlacement: { kind: "centerTab" },
    allowedPlacements: ["centerTab", "floatingPanel", "window"],
    requiredContext: ["editorSession"],
    canDock: false,
    canFloat: true,
    canOpenInWindow: true,
    canOpenInCenterTabs: true,
    singleton: false,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "entity.inspector",
    title: "Inspector",
    category: "inspector",
    domain: "scene",
    icon: "box",
    placement: { kind: "rightDock" },
    defaultPlacement: { kind: "rightDock" },
    allowedPlacements: ["rightDock", "floatingPanel"],
    requiredContext: ["editorSession"],
    canDock: true,
    canFloat: true,
    canOpenInWindow: false,
    canOpenInCenterTabs: false,
    singleton: true,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "diagnostics.problems",
    title: "Problems",
    category: "diagnostics",
    domain: "diagnostics",
    icon: "alert-triangle",
    placement: { kind: "bottomDock" },
    defaultPlacement: { kind: "bottomDock" },
    allowedPlacements: ["bottomDock", "floatingPanel", "window"],
    canDock: true,
    canFloat: true,
    canOpenInWindow: true,
    canOpenInCenterTabs: false,
    singleton: true,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "diagnostics.panel",
    title: "Diagnostics",
    category: "diagnostics",
    domain: "diagnostics",
    icon: "alert-triangle",
    placement: { kind: "rightDock" },
    defaultPlacement: { kind: "rightDock" },
    allowedPlacements: ["rightDock", "bottomDock", "floatingPanel", "window"],
    canDock: true,
    canFloat: true,
    canOpenInWindow: true,
    canOpenInCenterTabs: false,
    singleton: true,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "entity.properties",
    title: "Properties",
    category: "inspector",
    domain: "scene",
    icon: "box",
    placement: { kind: "rightDock" },
    defaultPlacement: { kind: "rightDock" },
    allowedPlacements: ["rightDock", "floatingPanel"],
    requiredContext: ["editorSession"],
    canDock: true,
    canFloat: true,
    canOpenInWindow: false,
    canOpenInCenterTabs: false,
    singleton: true,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "events.log",
    title: "Event Log",
    category: "system",
    domain: "windowing",
    subdomain: "event-bus",
    icon: "terminal",
    placement: { kind: "bottomDock" },
    defaultPlacement: { kind: "bottomDock" },
    allowedPlacements: ["bottomDock", "floatingPanel", "window"],
    canDock: true,
    canFloat: true,
    canOpenInWindow: true,
    canOpenInCenterTabs: false,
    singleton: true,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "tasks.monitor",
    title: "Tasks",
    category: "system",
    domain: "editor",
    subdomain: "tasks",
    icon: "check-circle",
    placement: { kind: "bottomDock" },
    defaultPlacement: { kind: "bottomDock" },
    allowedPlacements: ["bottomDock", "floatingPanel", "window"],
    canDock: true,
    canFloat: true,
    canOpenInWindow: true,
    canOpenInCenterTabs: false,
    singleton: true,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "cache.preview",
    title: "Preview Cache",
    category: "system",
    domain: "cache",
    icon: "gauge",
    placement: { kind: "bottomDock" },
    defaultPlacement: { kind: "bottomDock" },
    allowedPlacements: ["bottomDock", "floatingPanel", "window"],
    requiredContext: ["projectCache"],
    canDock: true,
    canFloat: true,
    canOpenInWindow: true,
    canOpenInCenterTabs: false,
    singleton: true,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "theme.controller",
    title: "Theme Controller",
    category: "settings",
    domain: "theme",
    icon: "paintbrush",
    placement: { kind: "window" },
    defaultPlacement: { kind: "window" },
    allowedPlacements: ["window", "modal"],
    canDock: false,
    canFloat: false,
    canOpenInWindow: true,
    canOpenInCenterTabs: false,
    singleton: true,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "settings.global",
    title: "Settings",
    category: "settings",
    domain: "settings",
    icon: "settings",
    placement: { kind: "window" },
    defaultPlacement: { kind: "window" },
    allowedPlacements: ["window"],
    canDock: false,
    canFloat: false,
    canOpenInWindow: true,
    canOpenInCenterTabs: false,
    singleton: true,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "cache.manager",
    title: "Cache Manager",
    category: "tools",
    domain: "cache",
    icon: "gauge",
    placement: { kind: "window" },
    defaultPlacement: { kind: "window" },
    allowedPlacements: ["window"],
    canDock: false,
    canFloat: false,
    canOpenInWindow: true,
    canOpenInCenterTabs: false,
    singleton: true,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "scripting.console",
    title: "Console",
    category: "debug",
    domain: "scripting",
    icon: "terminal",
    placement: { kind: "bottomDock" },
    defaultPlacement: { kind: "bottomDock" },
    allowedPlacements: ["bottomDock", "floatingPanel", "window"],
    canDock: true,
    canFloat: true,
    canOpenInWindow: true,
    canOpenInCenterTabs: false,
    singleton: true,
    render: RegisteredComponentPlaceholder,
  },
];
