import { RegisteredComponentPlaceholder } from "./componentHost";
import type { EditorComponentDefinition } from "./componentTypes";

export const builtinEditorComponents: EditorComponentDefinition[] = [
  {
    id: "project.explorer",
    title: "Project Explorer",
    category: "explorer",
    domain: "project",
    icon: "folder",
    description: "Project file tree and mod structure.",
    placement: { kind: "leftDock" },
    defaultPlacement: { kind: "leftDock" },
    allowedPlacements: ["leftDock", "rightDock", "floatingPanel"],
    requiredContext: ["editorSession"],
    canDock: true,
    canFloat: true,
    canOpenInWindow: false,
    canOpenInCenterTabs: false,
    singleton: true,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "assets.browser",
    title: "Assets",
    category: "explorer",
    domain: "assets",
    icon: "package",
    description: "Asset type browser and future thumbnail index.",
    placement: { kind: "leftDock" },
    defaultPlacement: { kind: "leftDock" },
    allowedPlacements: ["leftDock", "rightDock", "floatingPanel"],
    requiredContext: ["editorSession"],
    canDock: true,
    canFloat: true,
    canOpenInWindow: false,
    canOpenInCenterTabs: false,
    singleton: true,
    toolbar: {
      compact: true,
      controls: [
        {
          kind: "segmented",
          id: "viewMode",
          label: "View",
          defaultValue: "tree",
          options: [
            { id: "tree", label: "Tree", icon: "list-tree" },
            { id: "list", label: "List", icon: "list" },
            { id: "tiles", label: "Tiles", icon: "grid" },
          ],
        },
        {
          kind: "select",
          id: "kind",
          label: "Kind",
          defaultValue: "all",
          options: [
            { id: "all", label: "All" },
            { id: "image-2d", label: "Images" },
            { id: "tileset-2d", label: "Tilesets" },
            { id: "tile-ruleset-2d", label: "Rulesets" },
            { id: "tilemap-2d", label: "Tilemaps" },
            { id: "sprite-sheet-2d", label: "Sprites" },
          ],
        },
        { kind: "toggle", id: "issuesOnly", label: "Issues", icon: "alert-triangle", defaultValue: false },
        { kind: "action", id: "refresh", label: "Refresh", icon: "refresh" },
      ],
    },
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "files.browser",
    title: "Files",
    category: "explorer",
    domain: "project",
    icon: "folder",
    description: "Raw project filesystem view.",
    placement: { kind: "leftDock" },
    defaultPlacement: { kind: "leftDock" },
    allowedPlacements: ["leftDock", "rightDock", "floatingPanel"],
    requiredContext: ["editorSession"],
    canDock: true,
    canFloat: true,
    canOpenInWindow: false,
    canOpenInCenterTabs: false,
    singleton: true,
    toolbar: {
      compact: true,
      controls: [
        {
          kind: "segmented",
          id: "viewMode",
          label: "View",
          defaultValue: "tree",
          options: [
            { id: "tree", label: "Tree", icon: "list-tree" },
            { id: "flat", label: "Flat", icon: "list" },
          ],
        },
        {
          kind: "select",
          id: "fileFilter",
          label: "Filter",
          defaultValue: "all",
          options: [
            { id: "all", label: "All" },
            { id: "descriptors", label: "Descriptors" },
            { id: "raw", label: "Raw" },
            { id: "scripts", label: "Scripts" },
            { id: "scenes", label: "Scenes" },
          ],
        },
      ],
    },
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "scenes.browser",
    title: "Scenes",
    category: "explorer",
    domain: "scene",
    icon: "play",
    description: "Scene navigation list.",
    placement: { kind: "leftDock" },
    defaultPlacement: { kind: "leftDock" },
    allowedPlacements: ["leftDock", "rightDock", "floatingPanel"],
    requiredContext: ["editorSession"],
    canDock: true,
    canFloat: true,
    canOpenInWindow: false,
    canOpenInCenterTabs: false,
    singleton: true,
    toolbar: {
      compact: true,
      controls: [
        {
          kind: "segmented",
          id: "viewMode",
          label: "View",
          defaultValue: "list",
          options: [
            { id: "list", label: "List", icon: "list" },
            { id: "status", label: "Status", icon: "alert-triangle" },
          ],
        },
        { kind: "toggle", id: "visibleOnly", label: "Visible", icon: "play", defaultValue: false },
      ],
    },
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "scripts.browser",
    title: "Scripts",
    category: "explorer",
    domain: "scripting",
    icon: "terminal",
    description: "Scripts and packages navigation.",
    placement: { kind: "leftDock" },
    defaultPlacement: { kind: "leftDock" },
    allowedPlacements: ["leftDock", "rightDock", "floatingPanel"],
    requiredContext: ["editorSession"],
    canDock: true,
    canFloat: true,
    canOpenInWindow: false,
    canOpenInCenterTabs: false,
    singleton: true,
    toolbar: {
      compact: true,
      controls: [
        {
          kind: "segmented",
          id: "viewMode",
          label: "View",
          defaultValue: "tree",
          options: [
            { id: "tree", label: "Tree", icon: "list-tree" },
            { id: "packages", label: "Packages", icon: "package" },
            { id: "flat", label: "Flat", icon: "list" },
          ],
        },
        { kind: "toggle", id: "packagesOnly", label: "Packages", icon: "package", defaultValue: false },
      ],
    },
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "scene.hierarchy",
    title: "Scene Hierarchy",
    category: "explorer",
    domain: "scene",
    icon: "list-tree",
    placement: { kind: "leftDock" },
    defaultPlacement: { kind: "leftDock" },
    allowedPlacements: ["leftDock", "rightDock", "floatingPanel"],
    requiredContext: ["selectedScene"],
    canDock: true,
    canFloat: true,
    canOpenInWindow: false,
    canOpenInCenterTabs: false,
    singleton: true,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "project.overview",
    title: "Mod Overview",
    category: "workspace",
    domain: "project",
    icon: "box",
    description: "Summary of the active mod.",
    placement: { kind: "centerTab" },
    defaultPlacement: { kind: "centerTab" },
    allowedPlacements: ["centerTab", "floatingPanel", "window"],
    requiredContext: ["editorSession"],
    canDock: false,
    canFloat: true,
    canOpenInWindow: true,
    canOpenInCenterTabs: true,
    singleton: true,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "project.capabilities",
    title: "Capabilities",
    category: "workspace",
    domain: "project",
    icon: "box",
    description: "Capabilities declared by the active mod.",
    placement: { kind: "centerTab" },
    defaultPlacement: { kind: "centerTab" },
    allowedPlacements: ["centerTab", "floatingPanel", "window"],
    requiredContext: ["editorSession"],
    canDock: false,
    canFloat: true,
    canOpenInWindow: true,
    canOpenInCenterTabs: true,
    singleton: true,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "project.dependencies",
    title: "Dependencies",
    category: "workspace",
    domain: "project",
    icon: "package",
    description: "Dependency state for the active mod.",
    placement: { kind: "centerTab" },
    defaultPlacement: { kind: "centerTab" },
    allowedPlacements: ["centerTab", "floatingPanel", "window"],
    requiredContext: ["editorSession"],
    canDock: false,
    canFloat: true,
    canOpenInWindow: true,
    canOpenInCenterTabs: true,
    singleton: true,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "scene.preview",
    title: "Scene Preview",
    category: "preview",
    domain: "preview",
    subdomain: "scene",
    icon: "play",
    placement: { kind: "centerTab" },
    defaultPlacement: { kind: "centerTab" },
    allowedPlacements: ["centerTab", "floatingPanel", "window"],
    requiredContext: ["selectedScene"],
    canDock: false,
    canFloat: true,
    canOpenInWindow: true,
    canOpenInCenterTabs: true,
    singleton: false,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "file.manifest",
    title: "Manifest",
    category: "editor",
    domain: "modding",
    icon: "box",
    placement: { kind: "centerTab" },
    defaultPlacement: { kind: "centerTab" },
    allowedPlacements: ["centerTab", "floatingPanel", "window"],
    requiredContext: ["editorSession"],
    canDock: false,
    canFloat: true,
    canOpenInWindow: true,
    canOpenInCenterTabs: true,
    singleton: false,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "file.scene",
    title: "Scene",
    category: "editor",
    domain: "scene",
    icon: "play",
    placement: { kind: "centerTab" },
    defaultPlacement: { kind: "centerTab" },
    allowedPlacements: ["centerTab", "floatingPanel", "window"],
    requiredContext: ["editorSession"],
    canDock: false,
    canFloat: true,
    canOpenInWindow: true,
    canOpenInCenterTabs: true,
    singleton: false,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "file.scene-script",
    title: "Scene Script",
    category: "editor",
    domain: "scripting",
    icon: "terminal",
    placement: { kind: "centerTab" },
    defaultPlacement: { kind: "centerTab" },
    allowedPlacements: ["centerTab", "floatingPanel", "window"],
    requiredContext: ["editorSession"],
    canDock: false,
    canFloat: true,
    canOpenInWindow: true,
    canOpenInCenterTabs: true,
    singleton: false,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "file.package",
    title: "Package",
    category: "editor",
    domain: "scripting",
    icon: "package",
    placement: { kind: "centerTab" },
    defaultPlacement: { kind: "centerTab" },
    allowedPlacements: ["centerTab", "floatingPanel", "window"],
    requiredContext: ["editorSession"],
    canDock: false,
    canFloat: true,
    canOpenInWindow: true,
    canOpenInCenterTabs: true,
    singleton: false,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "file.script",
    title: "Script",
    category: "editor",
    domain: "scripting",
    icon: "terminal",
    placement: { kind: "centerTab" },
    defaultPlacement: { kind: "centerTab" },
    allowedPlacements: ["centerTab", "floatingPanel", "window"],
    requiredContext: ["editorSession"],
    canDock: false,
    canFloat: true,
    canOpenInWindow: true,
    canOpenInCenterTabs: true,
    singleton: false,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "file.texture",
    title: "Texture",
    category: "preview",
    domain: "assets",
    icon: "image",
    placement: { kind: "centerTab" },
    defaultPlacement: { kind: "centerTab" },
    allowedPlacements: ["centerTab", "floatingPanel", "window"],
    requiredContext: ["editorSession"],
    canDock: false,
    canFloat: true,
    canOpenInWindow: true,
    canOpenInCenterTabs: true,
    singleton: false,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "file.image-asset",
    title: "Image Asset",
    category: "editor",
    domain: "assets",
    icon: "image",
    placement: { kind: "centerTab" },
    defaultPlacement: { kind: "centerTab" },
    allowedPlacements: ["centerTab", "floatingPanel", "window"],
    requiredContext: ["editorSession"],
    canDock: false,
    canFloat: true,
    canOpenInWindow: true,
    canOpenInCenterTabs: true,
    singleton: false,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "file.raw-image",
    title: "Raw Image",
    category: "preview",
    domain: "assets",
    icon: "image",
    placement: { kind: "centerTab" },
    defaultPlacement: { kind: "centerTab" },
    allowedPlacements: ["centerTab", "floatingPanel", "window"],
    requiredContext: ["editorSession"],
    canDock: false,
    canFloat: true,
    canOpenInWindow: true,
    canOpenInCenterTabs: true,
    singleton: false,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "file.sprite",
    title: "Sprite",
    category: "editor",
    domain: "rendering_2d",
    icon: "image",
    placement: { kind: "centerTab" },
    defaultPlacement: { kind: "centerTab" },
    allowedPlacements: ["centerTab", "floatingPanel", "window"],
    requiredContext: ["editorSession"],
    canDock: false,
    canFloat: true,
    canOpenInWindow: true,
    canOpenInCenterTabs: true,
    singleton: false,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "file.atlas",
    title: "Atlas",
    category: "editor",
    domain: "rendering_2d",
    icon: "image",
    placement: { kind: "centerTab" },
    defaultPlacement: { kind: "centerTab" },
    allowedPlacements: ["centerTab", "floatingPanel", "window"],
    requiredContext: ["editorSession"],
    canDock: false,
    canFloat: true,
    canOpenInWindow: true,
    canOpenInCenterTabs: true,
    singleton: false,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "file.tileset",
    title: "Tileset",
    category: "editor",
    domain: "tileset",
    icon: "layers",
    placement: { kind: "centerTab" },
    defaultPlacement: { kind: "centerTab" },
    allowedPlacements: ["centerTab", "floatingPanel", "window"],
    requiredContext: ["editorSession"],
    canDock: false,
    canFloat: true,
    canOpenInWindow: true,
    canOpenInCenterTabs: true,
    singleton: false,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "file.tilemap",
    title: "Tilemap",
    category: "editor",
    domain: "tilemap",
    icon: "layers",
    placement: { kind: "centerTab" },
    defaultPlacement: { kind: "centerTab" },
    allowedPlacements: ["centerTab", "floatingPanel", "window"],
    requiredContext: ["editorSession"],
    canDock: false,
    canFloat: true,
    canOpenInWindow: true,
    canOpenInCenterTabs: true,
    singleton: false,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "file.config",
    title: "Config",
    category: "editor",
    domain: "editor",
    icon: "box",
    placement: { kind: "centerTab" },
    defaultPlacement: { kind: "centerTab" },
    allowedPlacements: ["centerTab", "floatingPanel", "window"],
    requiredContext: ["editorSession"],
    canDock: false,
    canFloat: true,
    canOpenInWindow: true,
    canOpenInCenterTabs: true,
    singleton: false,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "file.text",
    title: "Text",
    category: "editor",
    domain: "editor",
    icon: "terminal",
    placement: { kind: "centerTab" },
    defaultPlacement: { kind: "centerTab" },
    allowedPlacements: ["centerTab", "floatingPanel", "window"],
    requiredContext: ["editorSession"],
    canDock: false,
    canFloat: true,
    canOpenInWindow: true,
    canOpenInCenterTabs: true,
    singleton: false,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "file.binary",
    title: "Unsupported File",
    category: "workspace",
    domain: "assets",
    icon: "alert-triangle",
    placement: { kind: "centerTab" },
    defaultPlacement: { kind: "centerTab" },
    allowedPlacements: ["centerTab", "floatingPanel", "window"],
    requiredContext: ["editorSession"],
    canDock: false,
    canFloat: true,
    canOpenInWindow: true,
    canOpenInCenterTabs: true,
    singleton: false,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "entity.inspector",
    title: "Inspector",
    category: "inspector",
    domain: "scene",
    icon: "box",
    placement: { kind: "rightDock" },
    defaultPlacement: { kind: "rightDock" },
    allowedPlacements: ["rightDock", "floatingPanel"],
    requiredContext: ["editorSession"],
    canDock: true,
    canFloat: true,
    canOpenInWindow: false,
    canOpenInCenterTabs: false,
    singleton: true,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "diagnostics.problems",
    title: "Problems",
    category: "diagnostics",
    domain: "diagnostics",
    icon: "alert-triangle",
    placement: { kind: "bottomDock" },
    defaultPlacement: { kind: "bottomDock" },
    allowedPlacements: ["bottomDock", "floatingPanel", "window"],
    canDock: true,
    canFloat: true,
    canOpenInWindow: true,
    canOpenInCenterTabs: false,
    singleton: true,
    toolbar: {
      compact: true,
      controls: [
        {
          kind: "segmented",
          id: "level",
          label: "Level",
          defaultValue: "all",
          options: [
            { id: "all", label: "All", icon: "list" },
            { id: "error", label: "Errors", icon: "alert-triangle" },
            { id: "warning", label: "Warnings", icon: "gauge" },
          ],
        },
      ],
    },
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "diagnostics.panel",
    title: "Diagnostics",
    category: "diagnostics",
    domain: "diagnostics",
    icon: "alert-triangle",
    placement: { kind: "rightDock" },
    defaultPlacement: { kind: "rightDock" },
    allowedPlacements: ["rightDock", "bottomDock", "floatingPanel", "window"],
    canDock: true,
    canFloat: true,
    canOpenInWindow: true,
    canOpenInCenterTabs: false,
    singleton: true,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "entity.properties",
    title: "Properties",
    category: "inspector",
    domain: "scene",
    icon: "box",
    placement: { kind: "rightDock" },
    defaultPlacement: { kind: "rightDock" },
    allowedPlacements: ["rightDock", "floatingPanel"],
    requiredContext: ["editorSession"],
    canDock: true,
    canFloat: true,
    canOpenInWindow: false,
    canOpenInCenterTabs: false,
    singleton: true,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "events.log",
    title: "Event Log",
    category: "system",
    domain: "windowing",
    subdomain: "event-bus",
    icon: "terminal",
    placement: { kind: "bottomDock" },
    defaultPlacement: { kind: "bottomDock" },
    allowedPlacements: ["bottomDock", "floatingPanel", "window"],
    canDock: true,
    canFloat: true,
    canOpenInWindow: true,
    canOpenInCenterTabs: false,
    singleton: true,
    toolbar: {
      compact: true,
      controls: [
        {
          kind: "select",
          id: "category",
          label: "Category",
          defaultValue: "all",
          options: [
            { id: "all", label: "All" },
            { id: "window", label: "Window" },
            { id: "asset", label: "Asset" },
            { id: "workspace", label: "Workspace" },
            { id: "cache", label: "Cache" },
            { id: "settings", label: "Settings" },
          ],
        },
      ],
    },
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "tasks.monitor",
    title: "Tasks",
    category: "system",
    domain: "editor",
    subdomain: "tasks",
    icon: "check-circle",
    placement: { kind: "bottomDock" },
    defaultPlacement: { kind: "bottomDock" },
    allowedPlacements: ["bottomDock", "floatingPanel", "window"],
    canDock: true,
    canFloat: true,
    canOpenInWindow: true,
    canOpenInCenterTabs: false,
    singleton: true,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "cache.preview",
    title: "Preview Cache",
    category: "system",
    domain: "cache",
    icon: "gauge",
    placement: { kind: "bottomDock" },
    defaultPlacement: { kind: "bottomDock" },
    allowedPlacements: ["bottomDock", "floatingPanel", "window"],
    requiredContext: ["projectCache"],
    canDock: true,
    canFloat: true,
    canOpenInWindow: true,
    canOpenInCenterTabs: false,
    singleton: true,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "theme.controller",
    title: "Theme Controller",
    category: "settings",
    domain: "theme",
    icon: "paintbrush",
    placement: { kind: "window" },
    defaultPlacement: { kind: "window" },
    allowedPlacements: ["window", "modal"],
    canDock: false,
    canFloat: false,
    canOpenInWindow: true,
    canOpenInCenterTabs: false,
    singleton: true,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "settings.global",
    title: "Settings",
    category: "settings",
    domain: "settings",
    icon: "settings",
    placement: { kind: "window" },
    defaultPlacement: { kind: "window" },
    allowedPlacements: ["window"],
    canDock: false,
    canFloat: false,
    canOpenInWindow: true,
    canOpenInCenterTabs: false,
    singleton: true,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "cache.manager",
    title: "Cache Manager",
    category: "tools",
    domain: "cache",
    icon: "gauge",
    placement: { kind: "window" },
    defaultPlacement: { kind: "window" },
    allowedPlacements: ["window"],
    canDock: false,
    canFloat: false,
    canOpenInWindow: true,
    canOpenInCenterTabs: false,
    singleton: true,
    render: RegisteredComponentPlaceholder,
  },
  {
    id: "scripting.console",
    title: "Console",
    category: "debug",
    domain: "scripting",
    icon: "terminal",
    placement: { kind: "bottomDock" },
    defaultPlacement: { kind: "bottomDock" },
    allowedPlacements: ["bottomDock", "floatingPanel", "window"],
    canDock: true,
    canFloat: true,
    canOpenInWindow: true,
    canOpenInCenterTabs: false,
    singleton: true,
    render: RegisteredComponentPlaceholder,
  },
];
