import {
  ASSET_COMPONENTS,
  DIAGNOSTICS_COMPONENTS,
  FILE_COMPONENTS,
  INSPECTOR_COMPONENTS,
  TARGET_PANEL_COMPONENTS,
  PROJECT_COMPONENTS,
  SCENE_COMPONENTS,
  SYSTEM_COMPONENTS,
  UI_DOCUMENT_COMPONENTS,
} from "./builtin";
import type { EditorComponentDefinition } from "./componentTypes";

export const builtinEditorComponents = [
  ...PROJECT_COMPONENTS,
  ...ASSET_COMPONENTS,
  ...FILE_COMPONENTS,
  ...SCENE_COMPONENTS,
  ...INSPECTOR_COMPONENTS,
  ...TARGET_PANEL_COMPONENTS,
  ...DIAGNOSTICS_COMPONENTS,
  ...SYSTEM_COMPONENTS,
  ...UI_DOCUMENT_COMPONENTS,
] as const satisfies readonly EditorComponentDefinition<any>[];
