import type { UiNodePaletteItem, UiTemplateDefinition } from "./uiDocumentEditorTypes";

export const UI_NODE_PALETTE: UiNodePaletteItem[] = [
  {
    kind: "column",
    label: "Column",
    description: "Vertical layout container.",
    category: "layout",
    enabled: true,
  },
  {
    kind: "row",
    label: "Row",
    description: "Horizontal layout container.",
    category: "layout",
    enabled: true,
  },
  {
    kind: "panel",
    label: "Panel",
    description: "Container with background, border and padding.",
    category: "layout",
    enabled: true,
  },
  {
    kind: "stack",
    label: "Stack",
    description: "Overlapping layout container.",
    category: "layout",
    enabled: true,
  },
  {
    kind: "spacer",
    label: "Spacer",
    description: "Empty layout spacing.",
    category: "layout",
    enabled: true,
  },
  {
    kind: "text",
    label: "Text",
    description: "Static or bound text label.",
    category: "display",
    enabled: true,
  },
  {
    kind: "button",
    label: "Button",
    description: "Interactive clickable menu/control item.",
    category: "controls",
    enabled: true,
  },
  {
    kind: "image",
    label: "Image",
    description: "Image or sprite placeholder. Asset picker comes later.",
    category: "display",
    enabled: true,
  },
  {
    kind: "progress-bar",
    label: "Progress Bar",
    description: "Value display placeholder. Bindings come later.",
    category: "feedback",
    enabled: true,
  },
];

export const UI_TEMPLATE_DEFINITIONS: UiTemplateDefinition[] = [
  {
    kind: "empty-document",
    label: "Empty Document",
    description: "Start with a root container only.",
    category: "document",
    enabled: true,
    previewLabel: "Empty root",
  },
  {
    kind: "vertical-menu",
    label: "Vertical Menu",
    description: "Column with Start / Options / Quit buttons.",
    category: "menu",
    enabled: true,
    previewLabel: "START / OPTIONS / QUIT",
  },
  {
    kind: "button-row",
    label: "Button Row",
    description: "Horizontal row of buttons.",
    category: "menu",
    enabled: true,
    previewLabel: "Button row",
  },
  {
    kind: "health-bar",
    label: "Health Bar",
    description: "Label + progress bar HUD fragment.",
    category: "hud",
    enabled: true,
    previewLabel: "HP 100 / 100",
  },
  {
    kind: "ammo-counter",
    label: "Ammo Counter",
    description: "Ammo label and value HUD fragment.",
    category: "hud",
    enabled: true,
    previewLabel: "30 / 120",
  },
  {
    kind: "dialogue-box",
    label: "Dialogue Box",
    description: "Speaker, text area and continue hint.",
    category: "dialogue",
    enabled: true,
    previewLabel: "Dialogue",
  },
  {
    kind: "options-group",
    label: "Options Group",
    description: "Option labels and placeholder controls.",
    category: "menu",
    enabled: false,
    disabledReason: "Action/binding editor comes later.",
    previewLabel: "Options",
  },
  {
    kind: "inventory-slot",
    label: "Inventory Slot",
    description: "Item slot placeholder.",
    category: "inventory",
    enabled: false,
    disabledReason: "Inventory editor comes later.",
    previewLabel: "Slot",
  },
  {
    kind: "notification-toast",
    label: "Notification Toast",
    description: "Small notification panel.",
    category: "feedback",
    enabled: false,
    disabledReason: "Notification system comes later.",
    previewLabel: "Toast",
  },
];
